### PR TITLE
Improved the files based on Alex's suggestions

### PR DESCRIPTION
**Pull request by jrfarah**
Removed the redundant file, renamed the actual source file to match the rest of the filenames

thanks @alexandertuna :D

### CODE REVIEW

**Comment by alexandertuna** [comment]
Hey @jrfarah -- this requires edits to the Makefile too, right?

**Comment by alexandertuna** [comment]
Also @jrfarah, could you uncomment these lines as default?

https://github.com/jrfarah/MMFE8_DataFormats/blob/better/src/combineTPGBT.C#L385

I think the progress bar should be opt-out, not opt-in.

**Comment by alexandertuna** [comment]
Also @jrfarah, I get the following compiler warnings:

```
src/combineTPGBT.C:178:9: warning: unused variable 'num_changes_per_loop' [-Wunused-variable]
    int num_changes_per_loop = 1;
        ^
src/combineTPGBT.C:82:7: warning: unused variable 'ngbt' [-Wunused-variable]
        long ngbt = gbt_tree->GetEntries();
```

Could you take care of those?

**Comment by alexandertuna** [comment]
Last comment, I promise!

I think there are quite a few tabs in the code -- notice how the indentation rendered on github changes between lines 54 and 58:

https://github.com/jrfarah/MMFE8_DataFormats/blob/better/src/combineTPGBT.C#L54

Could you convert all of these to spaces? For emacs, it's as easy as:

```
# select everything, then
M-x untabify
M-x indent-region
```

I dunno about other editors, though.

**Comment by alexandertuna** [comment]
I lied, one more comment:

Can you call the progress bar occasionally, instead of every event? Like:

```
if (j % 1000 == 0) {
  // progress bar stuff
}
```

I think writing the progress bar to screen on every event is overkill.

EDIT: After monkeying with this for a few minutes, I would actually suggest:

```
if (i % 10000 == 0)
```

**Comment by jrfarah** [comment]
Fixing these now, I'll push them as individual commits so you can see they are all fixed @alexandertuna

**Comment by jrfarah** [comment]
Fixing these now, I'll push them as individual commits so you can see they are all fixed @alexandertuna

**Pull request merged**
