### PR TITLE
Change placement of GLIBS in Makefile to be compatible with non-mac

### PR DESCRIPTION
**Pull request by alexandertuna**
Hey @sezata / @crogan. Joe and I noticed the Makefile was crashing on his laptop running linux, and we think it's related to the order of the libraries in the compilation/linking step. 

c.f. https://root-forum.cern.ch/t/makefile-doesnt-work/24707/3

Pretty gnarly. I checked that it still compiles and runs fine on my laptop, same as before. Good to go.

cc @jrfarah

### CODE REVIEW

**Comment by jrfarah** [comment]
@alexandertuna  thanks for the fix, ill be making a pull request as soon as Mint warms up

**Comment by alexandertuna** [comment]
@jrfarah Sounds good. Give Ann/Chris a chance to look at this and merge, before making a new request, if that's okay.

And like we talked about: your request should have some additions to the Makefile and your script, only. If you did another `git add --all`, I will have strong words for you.

**Comment by jrfarah** [comment]
@alexandertuna understood. i figured out how to revert my last commit too so no worries about those generated files being added to the general repo XD

**Comment by jrfarah** [comment]
@alexandertuna i have pushed my changes to my fork, and will create a pull request as soon as i have the green light from you/Ann/Chris

and yes, before you ask i added the files individually and did not use `--all` haha

**Pull request merged**
